import React from "react";
import { useNavigate } from "react-router-dom";

function LandingPage() {
  const navigate = useNavigate();

  return (
    <div style={styles.container}>
      <section style={styles.hero}>
        <h1 style={styles.title}>Malaysian Sign Language AI Prototype</h1>
        <p style={styles.subtitle}>
          A Universiti Malaya group project that explores how computer vision
          and deep learning can support Malaysian Sign Language (MSL)
          recognition and inclusive communication.
        </p>

        <div style={styles.ctaRow}>
          <button
            onClick={() => navigate("/upload")}
            style={styles.primaryButton}
          >
            Try Upload & Translate
          </button>
          <button
            onClick={() => navigate("/learn")}
            style={styles.secondaryButton}
          >
            Learn How It Works
          </button>
        </div>

        <p style={styles.caption}>
          Designed and developed by Group 1 - <strong>SignBridge Lab</strong>, a student
          team covering project management, AI engineering, software development, UX
          design, and accessibility.
        </p>
      </section>

      <section style={styles.grid}>
        <div style={styles.card}>
          <h2 style={styles.cardTitle}>Upload & Predict</h2>
          <p style={styles.cardText}>
            Upload a short MSL video to see a prototype prediction of gloss and
            translation generated by our backend API.
          </p>
        </div>
        <div style={styles.card}>
          <h2 style={styles.cardTitle}>Real-time Camera</h2>
          <p style={styles.cardText}>
            Explore how a webcam feed could be integrated in the future to
            perform near real-time MSL recognition in everyday scenarios.
          </p>
        </div>
        <div style={styles.card}>
          <h2 style={styles.cardTitle}>Gamified MSL Learning</h2>
          <p style={styles.cardText}>
            A gamified learning module where new user is guided 
            with standard MSL in front of a live camera where 
            real time MSL prediction is given to user.
          </p>
        </div>
      </section>
    </div>
  );
}

const styles = {
  container: {
    display: "flex",
    flexDirection: "column",
    gap: "18px",
  },
  hero: {
    marginBottom: "8px",
  },
  title: {
    fontSize: "1.8rem",
    marginBottom: "6px",
    background:
      "linear-gradient(120deg, #4c1d95 0%, #7c3aed 30%, #1d4ed8 70%, #f59e0b 100%)",
    WebkitBackgroundClip: "text",
    color: "transparent",
  },
  subtitle: {
    fontSize: "0.95rem",
    color: "#4b5563",
    maxWidth: "640px",
    marginBottom: "12px",
  },
  ctaRow: {
    display: "flex",
    flexWrap: "wrap",
    gap: "10px",
    marginBottom: "8px",
  },
  primaryButton: {
    padding: "9px 18px",
    borderRadius: "999px",
    border: "none",
    cursor: "pointer",
    fontWeight: 600,
    fontSize: "0.95rem",
    background:
      "linear-gradient(120deg, #7c3aed 0%, #a855f7 40%, #facc15 100%)",
    color: "#111827",
    boxShadow: "0 10px 24px rgba(129,140,248,0.55)",
  },
  secondaryButton: {
    padding: "9px 18px",
    borderRadius: "999px",
    border: "1px solid #e5e7eb",
    cursor: "pointer",
    fontWeight: 500,
    fontSize: "0.9rem",
    background: "#f9fafb",
    color: "#4b5563",
  },
  caption: {
    fontSize: "0.8rem",
    color: "#6b7280",
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fit, minmax(220px, 1fr))",
    gap: "12px",
  },
  card: {
    borderRadius: "18px",
    border: "1px solid #e5e7eb",
    background: "#f9fafb",
    padding: "12px 14px",
  },
  cardTitle: {
    fontSize: "1rem",
    marginBottom: "4px",
    color: "#111827",
  },
  cardText: {
    fontSize: "0.9rem",
    color: "#4b5563",
  },
};

export default LandingPage;
